"""Remove PrivateNote model and related features

Revision ID: 00f6f2ec4cda
Revises: 692294fd39d6
Create Date: 2025-07-10 14:48:53.812485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00f6f2ec4cda'
down_revision = '692294fd39d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('private_note')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('private_note',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('alt_baslik_id', sa.INTEGER(), nullable=False),
    sa.Column('note_content', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['alt_baslik_id'], ['alt_baslik.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'alt_baslik_id', name=op.f('_user_alt_baslik_note_uc'))
    )
    # ### end Alembic commands ###
