"""Add PrivateNote model for user notes

Revision ID: 692294fd39d6
Revises: 6ffa2d641bae
Create Date: 2025-07-07 21:04:16.624850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '692294fd39d6'
down_revision = '6ffa2d641bae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('private_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alt_baslik_id', sa.Integer(), nullable=False),
    sa.Column('note_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alt_baslik_id'], ['alt_baslik.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'alt_baslik_id', name='_user_alt_baslik_note_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('private_note')
    # ### end Alembic commands ###
