"""Add PastExamMaterial table and relationship

Revision ID: 782046d7a2d8
Revises: d2a4fe99cabb
Create Date: 2025-07-13 11:56:06.106014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '782046d7a2d8'
down_revision = 'd2a4fe99cabb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('past_exam_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alt_baslik_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alt_baslik_id'], ['alt_baslik.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_column('quiz_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_type', sa.VARCHAR(length=50), server_default=sa.text("'normal'"), nullable=False))

    op.drop_table('past_exam_material')
    # ### end Alembic commands ###
