"""Remove notes column from AltBaslik

Revision ID: b63bcafc988c
Revises: 60ca84d3c628
Create Date: 2025-07-13 10:52:52.869538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b63bcafc988c'
down_revision = '60ca84d3c628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alt_baslik', schema=None) as batch_op:
        batch_op.drop_column('notlar')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alt_baslik', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notlar', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
