"""Update models: remove notes, add quiz_type, update UserQuizAttempt for details and quiz relationship

Revision ID: d2a4fe99cabb
Revises: e2dc727d6efe
Create Date: 2025-07-13 11:35:53.480631

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'd2a4fe99cabb'
down_revision = 'e2dc727d6efe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_quiz_attempt', schema=None) as batch_op:
        batch_op.alter_column('details',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_quiz_attempt', schema=None) as batch_op:
        batch_op.alter_column('details',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###
