"""Add quiz_type to Quiz model

Revision ID: e2dc727d6efe
Revises: b63bcafc988c
Create Date: 2025-07-13 11:00:36.123456 # Senin dosya tarihin

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2dc727d6efe' # Senin revizyon ID'n
down_revision = 'b63bcafc988c' # Bir önceki revizyon ID'n
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        # Önce nullable=True ile ekle ve varsayılan değeri ver
        batch_op.add_column(sa.Column('quiz_type', sa.String(length=50), nullable=True, server_default='normal'))

    # Mevcut tüm satırları 'normal' olarak güncelle
    # op.execute komutu doğrudan SQL çalıştırır.
    op.execute("UPDATE quiz SET quiz_type = 'normal' WHERE quiz_type IS NULL")

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        # Sonra sütunu nullable=False yap
        batch_op.alter_column('quiz_type',
                               existing_type=sa.String(length=50),
                               nullable=False,
                               existing_server_default='normal') # existing_server_default eklendi

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        # Downgrade işleminde tekrar nullable=True yap veya varsayılan değeri kaldır
        batch_op.alter_column('quiz_type',
                               existing_type=sa.String(length=50),
                               nullable=True,
                               existing_server_default='normal') # existing_server_default eklendi
        batch_op.drop_column('quiz_type')
    # ### end Alembic commands ###